# Generated by Django 5.1.1 on 2024-09-15 10:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import video_annotation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default=video_annotation.models.random_color, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('x', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('y', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('width', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('height', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='video_annotation.tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='video_annotation.video')),
            ],
        ),
    ]
